[shell]
# TODO(benkraft): Why doesn't chsh suffice?
program = "/bin/bash"

[font]
size = 14

[font.normal]
family = "Ubuntu Mono derivative Powerline"

[scrolling]
history = 100000

[window.dimensions]
columns = 90
lines = 40

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0004"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0008"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0009"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000A"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000C"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000D"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0014"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0019"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001A"
key = "Z"
mods = "Command"
